export const TAGLIST_ACTION_ADD = "TAGLIST_ACTION_ADD";
export const TAGLIST_ACTION_REMOVE = "TAGLIST_ACTION_REMOVE";
export const TAGLIST_ACTION_CHANGECOLOR = "TAGLIST_ACTION_CHANGECOLOR";

export const TAGLIST_ACTION_ADD_SUCCESS = "TAGLIST_ACTION_ADD_SUCCESS";
