export const LIST_ACTION_ADD = "LIST_ACTION_ADD";
export const LIST_ACTION_EDIT = "LIST_ACTION_EDIT";
export const LIST_ACTION_SETTAG = "LIST_ACTION_SETTAG";
export const LIST_ACTION_REMOVE = "LIST_ACTION_REMOVE";
