export const FILTER_ACTION_SELECT = "FILTER_ACTION_SELECT";
export const FILTER_ACTION_SEARCH = "FILTER_ACTION_SEARCH";
export const FILTER_ACTION_SET_SELECTED_TAGLIST = "SET_SELECTED_TAGLIST";
export const FILTER_ACTION_SEARCH_MODECHANGE =
  "FILTER_ACTION_SEARCH_MODECHANGE";

// display style
export const FILTER_MODE_SHOWITEM = "SHOW_ITEM";
export const FILTER_MODE_HIGHLIGHT = "HIGHLIGHT";
