export const LIST_ACTION_ADD = "LIST_ACTION_ADD";
export const LIST_ACTION_EDIT = "LIST_ACTION_EDIT";
export const LIST_ACTION_SETTAG = "LIST_ACTION_SETTAG";
export const LIST_ACTION_REMOVE = "LIST_ACTION_REMOVE";
export const LIST_ACTION_DRAG = "LIST_ACTION_DRAG";

export const LIST_ACTION_ADD_SUCCESS = "LIST_ACTION_ADD_SUCCESS";
